[package]
name = "sila"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.8.17"
serde = { version = "1.0", features = ["derive"] }
